In [1]:
import numpy as np
t=np.array([[1,2,3],[4,5,6]])
print(t)

[[1 2 3]
 [4 5 6]]


In [2]:
print(np.ndim(t)) #dimension

2


In [3]:
print(np.size(t))# size

6


In [4]:
print(np.shape(t))

(2, 3)


In [5]:
print(np.reshape(t,(2,3)))

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
y=np.array([[1,2],[3,4],[5,6],[7,8]])
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
print(np.reshape(y,(2,4)))

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
import import_ipynb
import numpyfunc
x1=int(input())
x2=int(input())
x3=int(input())
x4=int(input())
x5=int(input())
x6=int(input())

y1=int(input())
y2=int(input())
y3=int(input())
y4=int(input())
y5=int(input())
y6=int(input())
h=np.array([[x1,x2,x3],[x4,x5,x6]])
i=np.array([[y1,y2,y3],[y4,y5,y6]])
print(h)
print(i)
numpyfunc.shape(h)

1
2
3
4
5
6
7
8
9
1
2
3
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [1 2 3]]
(2, 3)


In [13]:
t=np.arange(1,10)
print(t)

[1 2 3 4 5 6 7 8 9]


In [18]:
t=np.arange(1,10,2)
print(t)
print(type(t))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [24]:
t=np.arange(1,11).reshape(2,5)
print(t)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# linspace 

In [34]:
f=np.linspace(1,2,8).reshape(4,2)
print(type(f))
print(f)

<class 'numpy.ndarray'>
[[1.         1.14285714]
 [1.28571429 1.42857143]
 [1.57142857 1.71428571]
 [1.85714286 2.        ]]
